In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
# NumPy main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [6,8,9]],
               [[11,12,13],
               [14,15,16],
               [17,18,19]]
               ])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a2.dtype

dtype('int64')

In [11]:
a1.size, a2.size , a3.size

(3, 6, 18)

In [12]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# Create NumPy Arrays

In [14]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
ones.dtype

dtype('float64')

In [16]:
type(ones)

numpy.ndarray

In [17]:
zeroes = np.zeros(5,dtype=int)

In [18]:
zeroes

array([0, 0, 0, 0, 0])

In [19]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[1, 9, 5, 4, 2],
       [3, 5, 0, 7, 3],
       [0, 3, 3, 3, 6]])

In [21]:
random_array_two = np.random.random((5,3))
random_array_two

array([[0.2680116 , 0.42375716, 0.35724568],
       [0.91552614, 0.83718039, 0.77808085],
       [0.35523408, 0.68521023, 0.60813298],
       [0.70412225, 0.47892686, 0.64257517],
       [0.57670816, 0.94813804, 0.21081844]])

In [22]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.03216277, 0.8789439 , 0.03066853],
       [0.75594734, 0.5401867 , 0.52510235],
       [0.1187967 , 0.50302341, 0.50113151],
       [0.87563377, 0.20478609, 0.32550808],
       [0.84448952, 0.48695673, 0.10748661]])

In [23]:
# Pseudo Random Numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10 , size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

# Viewing Arrays and Metrices

In [24]:
# Finding Unique  Element in Array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1

array([1, 2, 3])

In [26]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [28]:
a1[0]

1

In [29]:
a2[0][0]

1

In [30]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 12],
        [14, 15]]])

In [31]:
a3.shape

(2, 3, 3)

In [32]:
a3[:1,:3,:2]  # [ Dimension , Row , Column]

array([[[1, 2],
        [4, 5],
        [6, 8]]])

In [33]:
a4 = np.random.randint(10 , size=(3,2 ,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]]],


       [[[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]],

        [[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]]],


       [[[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [34]:
a4[2 ,1 ,0,:]

array([2, 3, 4, 1, 2])

##  Manipulating and Comparing Arrays

### Arithmatic

In [35]:
a1

array([1, 2, 3])

In [36]:
ones = np.ones(3)

In [37]:
a1+ones

array([2., 3., 4.])

In [38]:
a1-ones

array([0., 1., 2.])

In [39]:
a1*ones

array([1., 2., 3.])

In [40]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [41]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
# How can Reshape a2 to be compatible with a3 ?
# Works on this future

In [42]:
a1/ones

array([1., 2., 3.])

In [43]:
a1**2

array([1, 4, 9])

In [44]:
a1 %2

array([1, 0, 1])

In [45]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [46]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])



### Aggregation

In [47]:
listy_list = [1,2,3]
listy_list

[1, 2, 3]

In [48]:
sum(listy_list)

6

In [49]:
a1

array([1, 2, 3])

In [50]:
np.sum(a1)

6

Use python's method on python datatypes anf use numpy methods on NumPy Arrays

In [51]:
# Create A Massive NumPy Array

massive_array = np.random.random(100000)
massive_array

array([0.16494046, 0.36980809, 0.14644176, ..., 0.55947553, 0.62297663,
       0.05077999])

In [52]:
%timeit sum(massive_array)

4.93 ms ± 274 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [53]:
%timeit np.sum(massive_array)

22.9 µs ± 823 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [54]:


np.mean(a2)

3.5

In [55]:
np.max(a2)

6

In [56]:
np.std(a2)

1.707825127659933

In [57]:
np.var(a2)

2.9166666666666665

## Reshaping anf Transposing

In [58]:
a2.shape

(2, 3)

In [59]:
a3.shape

(2, 3, 3)

In [60]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [61]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [62]:
a2_reshape =  a2.reshape(2,3,1)

In [63]:
a2_reshape*a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 18,  24,  27]],

       [[ 44,  48,  52],
        [ 70,  75,  80],
        [102, 108, 114]]])

In [64]:

a2.T  # Switch axes i.e. swap row to column and column to row

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
# For multidimension , It interchange row and columns and ater that change that with dimension
# FOr Example (2,3,3)  => (3,3,2)

In [66]:
a2

array([[1, 2, 3],
       [4, 5, 6]])


# Dot Product 

In [67]:
np.random.seed(0)
mat1 = np.random.randint(10 , size=(5,3))
mat2 = np.random.randint(10 , size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [68]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [69]:
np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot Product Example  (Nut Butter Sales)

In [70]:
np.random.seed(0)

sales_amount = np.random.randint(20 , size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [71]:
# CReate Weekly Sales Dataframe
weekly_sales = pd.DataFrame(sales_amount ,index=["Monday" ,"Tuesday","Wednesday","Thursday","Friday"],
                            columns=["Almond Butter" ,"Peanut Butter" ,"Cashew Butter"])

In [72]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Monday                12             15              0
Tuesday                3              3              7
Wednesday              9             19             18
Thursday               4              6             12
Friday                 1              6              7

In [73]:
# Create prices array
prices  = np.array([10,8,12])

In [74]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"] ,
                            columns=["Almond Butter" ,"Peanut Butter" ,"Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [75]:
weekly_sales["Total ($)"] = np.dot(sales_amount ,prices.T)
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Monday                12             15              0        240
Tuesday                3              3              7        138
Wednesday              9             19             18        458
Thursday               4              6             12        232
Friday                 1              6              7        142

In [76]:
np.dot(sales_amount , prices.T)

array([240, 138, 458, 232, 142])

# Comparison Operator

In [77]:
a1

array([1, 2, 3])

In [78]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [80]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [81]:
a1 > 4

array([False, False, False])

In [82]:
a1< 1

array([False, False, False])

In [83]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

# Sorting in NumPy

In [84]:
random_array

array([[1, 9, 5, 4, 2],
       [3, 5, 0, 7, 3],
       [0, 3, 3, 3, 6]])

In [85]:
np.sort(random_array)

array([[1, 2, 4, 5, 9],
       [0, 3, 3, 5, 7],
       [0, 3, 3, 3, 6]])

In [86]:
np.argsort(random_array)

array([[0, 4, 3, 2, 1],
       [2, 0, 4, 1, 3],
       [0, 1, 2, 3, 4]])

In [87]:
a1

array([1, 2, 3])

In [88]:
np.argsort(a1)

array([0, 1, 2])

In [89]:
np.argmax(a1)

2

In [93]:
np.argmax(random_array , axis =1)

array([1, 3, 4])

In [94]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.argmax(a2, axis=1)

array([2, 2])

In [97]:
np.argmax(a2, axis=0)

array([1, 1, 1])

# Practical Example Numpy in Action 

<img src='V.jpeg'/>

In [101]:
# Turn an Image into NumPy Array

from matplotlib.image import imread


In [103]:
v = imread('V.jpeg')
type(v)

numpy.ndarray

In [104]:
v

array([[[ 7,  2,  8],
        [ 7,  2,  8],
        [ 7,  2,  8],
        ...,
        [ 9,  4, 11],
        [ 9,  4, 11],
        [ 9,  4, 11]],

       [[ 7,  2,  8],
        [ 7,  2,  8],
        [ 7,  2,  8],
        ...,
        [ 8,  3, 10],
        [ 8,  3, 10],
        [ 8,  3, 10]],

       [[ 7,  2,  8],
        [ 7,  2,  8],
        [ 7,  2,  8],
        ...,
        [ 8,  3, 10],
        [ 8,  3, 10],
        [ 8,  3, 10]],

       ...,

       [[ 6,  1,  7],
        [ 6,  1,  7],
        [ 7,  2,  8],
        ...,
        [11,  9, 20],
        [12,  9, 20],
        [14,  8, 18]],

       [[ 6,  1,  7],
        [ 6,  1,  7],
        [ 7,  2,  8],
        ...,
        [11,  9, 20],
        [12,  9, 20],
        [14,  8, 18]],

       [[ 6,  1,  7],
        [ 6,  1,  7],
        [ 7,  2,  8],
        ...,
        [11,  9, 20],
        [12,  9, 20],
        [14,  8, 18]]], dtype=uint8)

In [105]:
v.size , v.shape , v.ndim

(151164, (228, 221, 3), 3)