# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
               [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[9,8,7],
                [6,5,4],
                [3,2,1]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape , a1.dtype , type(a1)

((3,), dtype('int64'), numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape , a2.dtype , type(a2)

((2, 3), dtype('int64'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape , a3.dtype ,type(a3)

((2, 3, 3), dtype('int64'), numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones =  np.ones((10,2), dtype=int)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros((7,2,3) , dtype=int)
zeroes

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10,size=(7,2))
random_array

array([[5, 5],
       [4, 6],
       [5, 7],
       [3, 6],
       [6, 5],
       [1, 1],
       [5, 4]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2 = np.random.random(size=(3,5))
random_array_2

array([[0.8543798 , 0.06530704, 0.70675483, 0.21550442, 0.69406355],
       [0.43246492, 0.897542  , 0.51812742, 0.32571138, 0.93932362],
       [0.03141579, 0.07142633, 0.19750293, 0.24790572, 0.20931478]])

In [12]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 = np.random.randint(10 ,size=(4,6))
random_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Find the unique numbers in the array you just created
np.unique(random_array_3)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [14]:
# Find the 0'th index of the latest array you created
a1[0]

1

In [15]:
# Get the first 2 rows of latest array you created
a3[0 ,0 ,:]

array([1, 2, 3])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
a3[0,:2,:2]

array([[1, 2],
       [4, 5]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_one = np.random.randint(10,size=(3,5))
array_two = np.random.randint(10,size=(3,5))

In [18]:
# Add the two arrays together
array_one + array_two

array([[11,  8, 10, 11, 14],
       [12, 12,  3,  7,  8],
       [13,  6,  8,  9,  2]])

In [19]:
### Create another array of ones of shape (5, 3)
another_ones = np.ones((5,3), dtype=int)
another_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
# Try add the array of ones and the other most recent array together
# array_one + another_ones  :  operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
another_ones_again = np.ones((3,5), dtype=int)
another_ones_again

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# Subtract the new array of ones from the other most recent array
array_one - another_ones_again

array([[ 7, -1,  8,  1,  5],
       [ 2,  7,  1,  3,  1],
       [ 5,  3,  7,  5,  0]])

In [23]:
# Multiply the ones array with the latest array
array_one*another_ones_again

array([[8, 0, 9, 2, 6],
       [3, 8, 2, 4, 2],
       [6, 4, 8, 6, 1]])

In [24]:
# Take the latest array to the power of 2 using '**'
array_one**2

array([[64,  0, 81,  4, 36],
       [ 9, 64,  4, 16,  4],
       [36, 16, 64, 36,  1]])

In [25]:
# Do the same thing with np.square()
np.square(array_one)

array([[64,  0, 81,  4, 36],
       [ 9, 64,  4, 16,  4],
       [36, 16, 64, 36,  1]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(array_one)

4.6

In [27]:
# Find the maximum of the latest array using np.max()
np.max(array_one)

9

In [28]:
# Find the minimum of the latest array using np.min()
np.min(array_one)

0

In [29]:
# Find the standard deviation of the latest array
np.std(array_one)

2.8000000000000003

In [30]:
# Find the variance of the latest array
np.var(array_one)

7.840000000000002

In [51]:
# Reshape the latest array to (3, 5, 1)
array_one.reshape((3,5,1))

array([[[8],
        [0],
        [9],
        [2],
        [6]],

       [[3],
        [8],
        [2],
        [4],
        [2]],

       [[6],
        [4],
        [8],
        [6],
        [1]]])

In [52]:
# Transpose the latest array
array_one.T

array([[8, 3, 6],
       [0, 8, 4],
       [9, 2, 8],
       [2, 4, 6],
       [6, 2, 1]])

What does the transpose do?

In [54]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_one = np.random.randint(10,size=(3,3))
random_two = np.random.randint(10,size=(3,2))

In [55]:
# Perform a dot product on the two newest arrays you created
np.dot(random_one, random_two)

array([[ 97,  22],
       [153,  74],
       [ 79,  24]])

In [56]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
# one of size (3, 3) the other of size (3, 2)
random_one_new = np.random.randint(10,size=(4,3))
random_two_new = np.random.randint(10,size=(4,3))

In [58]:
# Perform a dot product on the two newest arrays you created
# np.dot(random_one_new, random_two_new) : 
# ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [59]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_one_new, random_two_new.T)

array([[113, 113,  57,  32],
       [ 36,  49,  42,  30],
       [128, 135,  72,  50],
       [ 56,  68,  68,  24]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [60]:
# Compare the two arrays with '>'
random_one_new >random_two_new

array([[False, False,  True],
       [False, False,  True],
       [ True,  True,  True],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [61]:
# Compare the two arrays with '>='
random_one_new >= random_two_new

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [62]:
# Find which elements of the first array are greater than 7
random_one_new >7

array([[ True, False, False],
       [False, False, False],
       [ True,  True,  True],
       [False,  True, False]])

In [63]:
# Which parts of each array are equal? (try using '==')
random_one_new == random_two_new

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [64]:
# Sort one of the arrays you just created in ascending order
np.sort(random_one_new)

array([[4, 7, 8],
       [1, 4, 7],
       [8, 8, 9],
       [0, 6, 8]])

In [65]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_one_new)

array([[2, 1, 0],
       [0, 1, 2],
       [1, 2, 0],
       [0, 2, 1]])

In [67]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_one_new,axis=0)

array([2, 2, 2])

In [68]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_one_new,axis=0)

array([3, 1, 0])

In [69]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_one_new,axis=1)

array([0, 2, 0, 1])

In [70]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_one_new,axis=0)

array([3, 1, 0])

In [71]:
# Create an array of normally distributed random numbers
np.random.normal(size=5)

array([ 0.21158701,  0.59704465, -0.89633518, -0.11198782,  1.46894129])

In [76]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0,100,  num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.